
export class Order {
_id: {};
date: { type: Date };
clientName: { type: String };
address: { type: String };
phoneNumber: { type: String };
fieldWorkPromissed: { type: Date };
printsPromissed: { type: Date };
projectName: { type: String };
legalDescription: { type: String };
orderPlacedBy: { type: String };
orderReceivedBy: {type: String };
referToFileNumber: {type: String };
referToFieldBookNumber: {type: String };
referToOrderNumber: {type: String };
fieldBook: { type: String };
page: { type: String };
section: { type: String };
township: { type: String };
range: { type: String };
partyChief: { type: String };
dateCompleted: { type: Date };
mail: { type: Number };
deliver: { type: Number };
pickup: { type: Number };
mailPrintsTo: { type: String };
deliverPrintsTo: { type: String };
printsAtTime: { type: String };
dateInvoice: { type: Date };
amountSetBy: { type: String };
invoiceTypedBy: { type: String };
courierFees: { type: Number };
applPermitFees: { type: Number };
isCOD: { type: Boolean };
orderNumber: { type: String };
fileNumber: { type: String };
price: { type: Number};
time: [];
}
